spring:
  application:
    name: customer-service
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false
      label: master
      enabled: false
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: true
        serviceName: ${spring.application.name}
        healthCheckPath: /actuator/health
        healthCheckInterval: 1s
        instanceId: ${spring.application.name}:${server.port}
    stream:
      bindings:
        timesheetEnteredIn:
          destination: timesheetEntered
          contentType: application/json
  rabbitmq:
    host: 10.4.65.55
    port: 5672
    username: admin
    password: admin

server:
  port: 9701